# Generated by Django 4.2.14 on 2024-08-29 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_forum_topic_post_topic'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Forum',
            new_name='Board',
        ),
        migrations.RenameField(
            model_name='topic',
            old_name='forum',
            new_name='board',
        ),
        migrations.AddField(
            model_name='author',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='author', to='forum.post'),
        ),
    ]
