# Generated by Django 4.2.14 on 2024-08-29 04:26

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_rename_forum_board_rename_forum_topic_board_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(blank=True, max_length=40)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatarimages/')),
                ('bio', tinymce.models.HTMLField()),
                ('rizz', models.IntegerField(default=0)),
                ('slug', models.SlugField(blank=True, max_length=400, unique=True)),
                ('post', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='forum.post')),
            ],
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
